export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/',
  CASH_SHIFTS: '/caja',
  SALES: '/ventas',
  SALES_NEW: '/ventas/nueva',
  SALE_INVOICE: '/ventas/:id/comprobante',
  SALE_RETURNS: '/devoluciones',
  PURCHASES: '/compras',
  PURCHASES_NEW: '/compras/nueva',
  PURCHASES_DETAIL: '/compras/:id',
  GOODS_RECEIPTS: '/recepciones',
  GOODS_RECEIPTS_NEW: '/recepciones/nueva',
  GOODS_RECEIPTS_DETAIL: '/recepciones/:id',
  ACCOUNTS_PAYABLE: '/cuentas-por-pagar',
  PRODUCTS: '/productos',
  INVENTORY: '/inventario',
  SUPPLIERS: '/proveedores',
  CUSTOMERS: '/clientes',
  CUSTOMER_STATEMENT: '/clientes/:id/cuenta',
  REPORTS: '/reportes',
  SETTINGS: '/configuracion',
  AFIP_SETTINGS: '/configuracion/afip',
} as const;
