export enum ErrorCode {
  // Auth
  UNAUTHORIZED           = 'UNAUTHORIZED',
  FORBIDDEN              = 'FORBIDDEN',
  INVALID_CREDENTIALS    = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED          = 'TOKEN_EXPIRED',
  TOKEN_INVALID          = 'TOKEN_INVALID',

  // Tenant
  TENANT_NOT_FOUND       = 'TENANT_NOT_FOUND',
  TENANT_INACTIVE        = 'TENANT_INACTIVE',
  TENANT_MISMATCH        = 'TENANT_MISMATCH',

  // Validation
  VALIDATION_ERROR       = 'VALIDATION_ERROR',
  INVALID_INPUT          = 'INVALID_INPUT',

  // Resource
  NOT_FOUND              = 'NOT_FOUND',
  ALREADY_EXISTS         = 'ALREADY_EXISTS',
  CONFLICT               = 'CONFLICT',

  // Business rules
  INSUFFICIENT_STOCK     = 'INSUFFICIENT_STOCK',
  SHIFT_ALREADY_OPEN     = 'SHIFT_ALREADY_OPEN',
  SHIFT_NOT_OPEN         = 'SHIFT_NOT_OPEN',
  PURCHASE_NOT_EDITABLE  = 'PURCHASE_NOT_EDITABLE',
  SALE_NOT_CANCELLABLE   = 'SALE_NOT_CANCELLABLE',

  // General
  INTERNAL_ERROR         = 'INTERNAL_ERROR',
  NOT_IMPLEMENTED        = 'NOT_IMPLEMENTED',
}
